require: rubocop-rails

AllCops:
  Exclude:
    - Gemfile
  NewCops: enable
  SuggestExtensions: false

Layout/LineLength:
  Exclude:
    - bin/bundle

Metrics/CyclomaticComplexity:
  Exclude:
    - bin/bundle

Metrics/MethodLength:
  Exclude:
    - bin/bundle

Metrics/PerceivedComplexity:
  Exclude:
    - bin/bundle

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false
